sudo: required
language: node_js
node_js:
    - "10.8.0"
install:
  - npm i
script:
  - npx ng lint
  - rm -rf ./src/assets/{imgs,data}
  - npx ng test --watch=false
  - BUILD=`date +%s`; sed -ie "s/BUILD/$BUILD/g" ./src/environments/environment.prod.ts
  - npx ng build --prod --deploy-url /waterfall/ --base-href /waterfall/
  - cp src/404.html dist/waterfall
cache:
    directories:
      - node_modules
deploy:
  - provider: pages
    local-dir: dist/waterfall
    github-token: $github
    skip-cleanup: true
    keep-history: true
